# Generated by Django 4.2.7 on 2024-02-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_model',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
